development:
  adapter: redis
  url: <%=  ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" }%>
  channel_prefix: chunkmaster-chat

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: chunkmaster_production
